# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5bbb30ce5b21024e1afa5e76c927a97c1324598a1c833a80462a7c6ff76140bcb1213e0ead667473e7060dd71dd94d3ad3201e761f4b856cd8506f0930418db

test:
  secret_key_base: 3b85a9c9519a173c020a45c81d0a1af9ad1a9436cc17ad0fc09379762a5bfb8ddd40c138291505d7b5fedbff9c5c8fdbea7f841b42338ecba845f6f37d4c33b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
